# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings

# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

lang: en

author:
  name: Hans De Winter
  email:
    - hans@silicos-it.be
    - hans.dewinter@uantwerpen.be

google_analytics: G-LS6PZHT6LV  # Replace with your Google Analytics 4 Measurement ID

title: Silicos-it
tagline: Computational drug design at your fingertips   # it will display as the sub-title
description: >- # this means to ignore newlines until "baseurl:"
  Computational drug design services such as molecular dynamics, pharmacophore modeling, 
  chemo-informatics.
copyright: Â© 2010-2026

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.silicos-it.be" # the base hostname & protocol for your site, e.g. http://example.com

social:
  name: Hans De Winter
  email:
    - hans@silicos-it.be
    - hans.dewinter@uantwerpen.be
  links:
    - { platform: github,   user_url: "https://github.com/silicos-it" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/company/silicos-it/about/" }

# Build settings
theme: minima
minima:
  skin: auto
  social_links:
    - { platform: github,   user_url: "https://github.com/silicos-it" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/company/silicos-it/about/" }
  date_format: "%b %-d, %Y"
   

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-last-modified-at


# Header pages
header_pages:
- who_are_we.md
- services.md
- software.md
- posts.md

# Blog posts
show_excerpts: true
#paginate: 5
#paginate_path: "/blogs/page:num/"
#plugins:
#  - jekyll-paginate
#  - jekyll-feed
#  - jekyll-sitemap


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
